# -*- coding: utf-8 -*-
import matplotlib

matplotlib.use('Agg')

import os, sys
import yaml
from argparse import ArgumentParser
from time import gmtime, strftime
from shutil import copy

from frames_dataset import FramesDataset

from modules.generator import OcclusionAwareGenerator
from modules.discriminator import MultiScaleDiscriminator
from modules.keypoint_detector import KPDetector
from modules.dense_motion import DenseMotionNetwork
from modules.RDloss import VideoCompressor

import torch

from train import train
from reconstruction import reconstruction
from animate import animate
import random
import numpy as np


def seed_torch(seed=1234):
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)  # 为了禁止hash随机化，使得实验可复现
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)  # if you are using multi-GPU.
    torch.backends.cudnn.benchmark = False
    torch.backends.cudnn.deterministic = True


def build_cfte_branch(config, device_id, verbose=False, branch_name='past'):
    """Build one complete CFTE branch: generator + compact-feature extractor + entropy model."""
    generator = OcclusionAwareGenerator(**config['model_params']['generator_params'],
                                        **config['model_params']['common_params'])
    kp_detector = KPDetector(**config['model_params']['kp_detector_params'],
                             **config['model_params']['common_params'])
    videocompressor = VideoCompressor(**config['model_params']['videocompressor_params'])

    if torch.cuda.is_available():
        generator.to(device_id)
        kp_detector.to(device_id)
        videocompressor.to(device_id)

    if verbose:
        print('===== %s CFTE generator =====' % branch_name)
        print(generator)
        print('===== %s CFTE kp_detector =====' % branch_name)
        print(kp_detector)
        print('===== %s CFTE videocompressor =====' % branch_name)
        print(videocompressor)

    return generator, kp_detector, videocompressor


if __name__ == "__main__":

    seed_torch(seed=1234)

    if sys.version_info[0] < 3:
        raise Exception("You must use Python 3 or higher. Recommended version is Python 3.7")

    parser = ArgumentParser()
    parser.add_argument("--config", default="./config/vox-256.yaml")
    parser.add_argument("--mode", default="train", choices=["train", "reconstruction", "animate"])
    parser.add_argument("--log_dir", default='./checkpoint_new/L4_superposition/')

    parser.add_argument("--checkpoint", default=None, help="path to checkpoint to restore")
    parser.add_argument("--device_ids", default="0", type=lambda x: list(map(int, x.split(','))),
                        help="Names of the devices comma separated.")
    parser.add_argument("--verbose", dest="verbose", action="store_true", help="Print model architecture")
    parser.set_defaults(verbose=False)

    opt = parser.parse_args()
    with open(opt.config) as f:
        config = yaml.safe_load(f)

    if opt.checkpoint is not None:
        log_dir = os.path.join(*os.path.split(opt.checkpoint)[:-1])
    else:
        log_dir = os.path.join(opt.log_dir, os.path.basename(opt.config).split('.')[0])
        # log_dir += ' ' + strftime("%d_%m_%y_%H.%M.%S", gmtime())

    # Shared-weight superposition CFTE:
    # build one CFTE branch and apply the same modules to the past and future references.
    # The model still produces prediction_past and prediction_future, but both predictions
    # are generated by the same kp_detector / videocompressor / generator parameters.
    generator_shared, kp_detector_shared, videocompressor_shared = build_cfte_branch(
        config, opt.device_ids[0], opt.verbose, branch_name='shared')

    generator_past = generator_shared
    generator_future = generator_shared
    kp_detector_past = kp_detector_shared
    kp_detector_future = kp_detector_shared
    videocompressor_past = videocompressor_shared
    videocompressor_future = videocompressor_shared

    discriminator = MultiScaleDiscriminator(**config['model_params']['discriminator_params'],
                                            **config['model_params']['common_params'])

    if torch.cuda.is_available():
        discriminator.to(opt.device_ids[0])
    if opt.verbose:
        print('===== discriminator =====')
        print(discriminator)

    dataset = FramesDataset(is_train=(opt.mode == 'train'), **config['dataset_params'])

    if not os.path.exists(log_dir):
        os.makedirs(log_dir)
    if not os.path.exists(os.path.join(log_dir, os.path.basename(opt.config))):
        copy(opt.config, log_dir)

    if opt.mode == 'train':
        print("Training shared-weight superposition CFTE with two reference frames...")
        train(config,
              generator_past, generator_future,
              discriminator,
              kp_detector_past, kp_detector_future,
              videocompressor_past, videocompressor_future,
              opt.checkpoint, log_dir, dataset, opt.device_ids)

    elif opt.mode == 'reconstruction':
        print("Reconstruction with the past branch only...")
        reconstruction(config, generator_past, kp_detector_past, videocompressor_past, opt.checkpoint, log_dir, dataset)

    elif opt.mode == 'animate':
        print("Animate with the past branch only...")
        animate(config, generator_past, kp_detector_past, videocompressor_past, opt.checkpoint, log_dir, dataset)
